// Generated by CoffeeScript 1.3.3
(function() {

  requirejs(['jquery', 'modules/stations/collections/stations', 'modules/stations/views/list'], function($, Stations, ListView) {
    var collection, view;
    collection = new Stations;
    view = new ListView({
      collection: collection
    });
    $('#container').append(view.render().el);
    return collection.fetch();
  });

}).call(this);
